apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-frontend
  namespace: poll-app
  labels:
    app: poll-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-frontend
  template:
    metadata:
      labels:
        app: poll-frontend
    spec:
      containers:
      - name: poll-frontend
        # Replace this placeholder with your actual image name after pushing to Artifact Registry
        image: us-central1-docker.pkg.dev/gen-lang-client-0646199746/poll-app-images/poll-frontend:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: poll-frontend
  namespace: poll-app
spec:
  selector:
    app: poll-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer 